apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: student-pvc
spec:
  storageClassName: ""   # use the static PV, not the default storageclass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
