apiVersion: v1
kind: Pod
metadata:
  name: net-app
  labels:
    app: net-app
spec:
  containers:
    - name: web
      image: python:3.11-alpine3.19
      command: ["python3", "-m", "http.server", "8000", "--bind", "0.0.0.0"]
      ports:
        - containerPort: 8000
